/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jhonatan
 */
public class practica extends javax.swing.JFrame {

    /**
     * Creates new form practica
     */
    public practica() {
        initComponents();
        this.setLocationRelativeTo(null);
        initial_capital_letter.setVisible(true);
        num.setEnabled(false);
        this.setTitle("String manager");
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        show = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        spanish = new javax.swing.JButton();
        english = new javax.swing.JButton();
        information = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        letter_finder = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        may = new javax.swing.JButton();
        min = new javax.swing.JButton();
        numero = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name_MAY = new javax.swing.JLabel();
        mane_MIN = new javax.swing.JLabel();
        total_characters = new javax.swing.JLabel();
        initial_capital_letter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Your name:");

        nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        show.setBackground(new java.awt.Color(255, 0, 0));
        show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        show.setText("SHOW");
        show.setEnabled(false);
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 255, 51));
        reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset.setText("RESET");
        reset.setEnabled(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        spanish.setBackground(new java.awt.Color(255, 102, 0));
        spanish.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        spanish.setText("Sp");
        spanish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spanishActionPerformed(evt);
            }
        });

        english.setBackground(new java.awt.Color(0, 0, 255));
        english.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        english.setText("En");
        english.setEnabled(false);
        english.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishActionPerformed(evt);
            }
        });

        information.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Your name is: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Your name in MAY:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Your name in MIN:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total caracters:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Initial capital letter:");

        letter_finder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Letter finder", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        letter_finder.setToolTipText("letter finder");
        letter_finder.setName("letter finder"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Type a number:");

        num.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numKeyTyped(evt);
            }
        });

        search.setBackground(new java.awt.Color(255, 255, 0));
        search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search.setText("SEARCH");
        search.setEnabled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        may.setBackground(new java.awt.Color(0, 0, 255));
        may.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        may.setText("MAY");
        may.setEnabled(false);
        may.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayActionPerformed(evt);
            }
        });

        min.setBackground(new java.awt.Color(255, 102, 0));
        min.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        min.setText("MIN");
        min.setEnabled(false);
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });

        numero.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        numero.setText("?");

        javax.swing.GroupLayout letter_finderLayout = new javax.swing.GroupLayout(letter_finder);
        letter_finder.setLayout(letter_finderLayout);
        letter_finderLayout.setHorizontalGroup(
            letter_finderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letter_finderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(letter_finderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(letter_finderLayout.createSequentialGroup()
                        .addComponent(num)
                        .addGap(52, 52, 52)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(letter_finderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(may)
                    .addComponent(min)))
        );
        letter_finderLayout.setVerticalGroup(
            letter_finderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letter_finderLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(letter_finderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(letter_finderLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(search))
                    .addGroup(letter_finderLayout.createSequentialGroup()
                        .addComponent(may)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(min)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(letter_finderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numero)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        name_MAY.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        mane_MIN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        total_characters.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        initial_capital_letter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout informationLayout = new javax.swing.GroupLayout(information);
        information.setLayout(informationLayout);
        informationLayout.setHorizontalGroup(
            informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mane_MIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(informationLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(informationLayout.createSequentialGroup()
                        .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informationLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_characters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(informationLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(initial_capital_letter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(informationLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_MAY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(letter_finder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        informationLayout.setVerticalGroup(
            informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name_MAY, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mane_MIN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_characters))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(initial_capital_letter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(letter_finder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(english)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spanish))
                            .addComponent(information, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spanish)
                    .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        name.setText(nombre.getText());
        name_MAY.setText((name.getText()).toUpperCase());
        mane_MIN.setText((name.getText()).toLowerCase());
        char[]  arrayChar = (name.getText()).toCharArray();
        total_characters.setText(String.valueOf(arrayChar.length));
        String cadena = nombre.getText();
        String d="";
        if (cadena.length()>0){
            search.setEnabled(true);
             char primer_letra = cadena.charAt(0);
             for (int i=1;i<cadena.length();i++){
                 char c = cadena.charAt(i);
                 c = Character.toLowerCase(cadena.charAt(i));
                    if (cadena.charAt(i-1) == ' '){
                       c = Character.toUpperCase(cadena.charAt(i));
                    }
             d = d + c;
             }
            cadena = Character.toUpperCase(primer_letra)+d;
             initial_capital_letter.setText(cadena); 
        } 
        reset.setEnabled(true);
        show.setEnabled(false);
        num.setEnabled(true);
    }//GEN-LAST:event_showActionPerformed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        
    }//GEN-LAST:event_showMouseClicked

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        String cadena = nombre.getText();       
          if (cadena.length()>0){
            show.setEnabled(true);
          }       
    }//GEN-LAST:event_nombreActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        nombre.setText(null);
        num.setText(null);
        name.setText(null);
        mane_MIN.setText(null);
        name_MAY.setText(null);
        total_characters.setText(null);
        numero.setText("?");
        initial_capital_letter.setText(null);
        min.setEnabled(false);
        search.setEnabled(false);
        may.setEnabled(false);
        reset.setEnabled(false);
        show.setEnabled(false);
        num.setEnabled(false);
    }//GEN-LAST:event_resetActionPerformed

    private void spanishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spanishActionPerformed
        reset.setText("LIMPIAR");
        show.setText("MOSTRAR");
        spanish.setText("Sp");
        jLabel2.setText("Tu nombre:");
        english.setText("En");
        jLabel1.setText("Tu nombre es:");
        jLabel3.setText("Tu nombre en MAY:");
        jLabel4.setText("Tu nombre en MIN:");
        jLabel5.setText("Total caracteres:");
        jLabel6.setText("Iniciales en mayúsculas:");
        jLabel7.setText("Digite un número:");
        search.setText("BUSCAR");
        information.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));
        letter_finder.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscador de letras"));
        spanish.setEnabled(false); 
        english.setEnabled(true); 
        this.setTitle("Administrador de cadenas");
    }//GEN-LAST:event_spanishActionPerformed

    private void englishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishActionPerformed
        reset.setText("RESET");
        show.setText("SHOW");
        spanish.setText("Sp");
        jLabel2.setText("Your name:");
        english.setText("En");
        jLabel1.setText("Your name is:");
        jLabel3.setText("Your name in MAY:");
        jLabel4.setText("Your name in MIN:");
        jLabel5.setText("Total characters:");
        jLabel6.setText("Inittial capitals characters::");
        jLabel7.setText("Type a number:");
        search.setText("SEARCH");
        information.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        letter_finder.setBorder(javax.swing.BorderFactory.createTitledBorder("Ietter finder"));
        english.setEnabled(false);
        spanish.setEnabled(true); 
        this.setTitle("String manager");
    }//GEN-LAST:event_englishActionPerformed

    private void mayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayActionPerformed
        String numCadena = num.getText(); 
        String cadena = nombre.getText();
        int numEntero = Integer.parseInt(numCadena);
        String sSubCadena = cadena.substring(numEntero-1,numEntero);
        numero.setText(sSubCadena.toUpperCase());
        may.setEnabled(false);
        min.setEnabled(true);
    }//GEN-LAST:event_mayActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        String numCadena = num.getText(); 
        String cadena = nombre.getText();
        int numEntero = Integer.parseInt(numCadena);
        String sSubCadena = cadena.substring(numEntero-1,numEntero);
        numero.setText(sSubCadena.toLowerCase());
        min.setEnabled(false);
        may.setEnabled(true);
    }//GEN-LAST:event_minActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
       char nom = evt.getKeyChar();
        if( Character.isLetter(nom)|| nom == ' '){
        }else{
           evt.consume();
           getToolkit().beep();
        }           
    }//GEN-LAST:event_nombreKeyTyped

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
      String numCadena = num.getText(); 
      String cadena = nombre.getText();
      int numEntero = Integer.parseInt(numCadena);
      String sSubCadena = cadena.substring(numEntero-1,numEntero);
        numero.setText(sSubCadena.toUpperCase());
        min.setEnabled(true);
        may.setEnabled(false);
    }//GEN-LAST:event_searchActionPerformed

    private void numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyTyped
        char num = evt.getKeyChar();
        if( Character.isDigit(num)){
        }else{
           evt.consume();
           getToolkit().beep();
        }
    }//GEN-LAST:event_numKeyTyped

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
     show.setEnabled(nombre.getText().length() != 0);
    }//GEN-LAST:event_nombreKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton english;
    private javax.swing.JPanel information;
    private javax.swing.JLabel initial_capital_letter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel letter_finder;
    private javax.swing.JLabel mane_MIN;
    private javax.swing.JButton may;
    private javax.swing.JButton min;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name_MAY;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField num;
    private javax.swing.JLabel numero;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JButton show;
    private javax.swing.JButton spanish;
    private javax.swing.JLabel total_characters;
    // End of variables declaration//GEN-END:variables
}
