/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Family
 */
public class Colors extends javax.swing.JFrame {
    /**
     * Creates new form Colors
     */ 
    public Colors() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbColors = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblColorSelected = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblChangeColor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPreviousColor1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        new_color = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colors");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Colors");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 670, 40);

        cmbColors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yellow", "Red", "Blue", "Green", "Black", "White", "Brown" }));
        jPanel1.add(cmbColors);
        cmbColors.setBounds(40, 90, 310, 30);

        jLabel2.setText("Choose a color:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("The color selected is:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 190, 140, 30);

        lblColorSelected.setText("...");
        jPanel1.add(lblColorSelected);
        lblColorSelected.setBounds(170, 190, 180, 30);

        jButton1.setText("What color did you select?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 140, 310, 40);

        lblChangeColor.setText("...");
        jPanel1.add(lblChangeColor);
        lblChangeColor.setBounds(40, 250, 140, 70);

        jLabel5.setText("Current color:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 230, 140, 14);

        jLabel6.setText("Previous color:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 230, 140, 14);

        lblPreviousColor1.setText("...");
        jPanel1.add(lblPreviousColor1);
        lblPreviousColor1.setBounds(210, 250, 140, 70);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add new colors"));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel4.setText("Color name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 30, 230, 20);

        new_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_colorActionPerformed(evt);
            }
        });
        jPanel2.add(new_color);
        new_color.setBounds(20, 60, 220, 30);

        jButton2.setText("Add color to combobox");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 100, 220, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(380, 60, 270, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i=0;
        String color;
        String d[] = new String [1];
        lblPreviousColor1.setText(lblColorSelected.getText());
        color = cmbColors.getSelectedItem().toString();
        d[i]=color;
        lblColorSelected.setText(d[i]);
        lblChangeColor.setText(d[i]);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void new_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_colorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         cmbColors.addItem(new_color.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbColors;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChangeColor;
    private javax.swing.JLabel lblColorSelected;
    private javax.swing.JLabel lblPreviousColor1;
    private javax.swing.JTextField new_color;
    // End of variables declaration//GEN-END:variables
}
