
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Random;
import java.util.Vector;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jhonatan
 */
public class NumberRace extends javax.swing.JFrame {


    /**
     * Creates new form NumberRace
     */
    public NumberRace() {
        initComponents();
         this.setLocationRelativeTo(null); 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mesa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        dices = new javax.swing.JPanel();
        dice_1 = new javax.swing.JLabel();
        dice_2 = new javax.swing.JLabel();
        suma = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        try_again = new javax.swing.JButton();
        en = new javax.swing.JButton();
        es = new javax.swing.JButton();
        box = new javax.swing.JComboBox<>();
        play_2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        scores = new javax.swing.JPanel();
        player = new javax.swing.JLabel();
        points = new javax.swing.JLabel();
        missing = new javax.swing.JLabel();
        player_2 = new javax.swing.JLabel();
        point_2 = new javax.swing.JLabel();
        missing_2 = new javax.swing.JLabel();
        pairs = new javax.swing.JPanel();
        jugadores = new javax.swing.JComboBox<>();
        level = new javax.swing.JLabel();
        about_of = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("number race");
        setIconImage(getIconImage());

        mesa.setBackground(new java.awt.Color(247, 245, 245));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/auto.gif"))); // NOI18N

        title.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText(" number race");

        dices.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DICES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        dice_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N

        dice_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N

        suma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        suma.setText("#");

        javax.swing.GroupLayout dicesLayout = new javax.swing.GroupLayout(dices);
        dices.setLayout(dicesLayout);
        dicesLayout.setHorizontalGroup(
            dicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dicesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(dice_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(dice_2)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(suma)
                .addGap(110, 110, 110))
        );
        dicesLayout.setVerticalGroup(
            dicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dicesLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(dicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dice_1)
                    .addComponent(dice_2))
                .addGap(7, 7, 7)
                .addComponent(suma)
                .addContainerGap())
        );

        play.setText("play");
        play.setEnabled(false);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        try_again.setText("try again");
        try_again.setEnabled(false);
        try_again.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try_againActionPerformed(evt);
            }
        });

        en.setText("EN");
        en.setEnabled(false);
        en.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enActionPerformed(evt);
            }
        });

        es.setText("ES");
        es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esActionPerformed(evt);
            }
        });

        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "basic[50]", "medium[100]", "expert[200]" }));

        play_2.setText("start game");
        play_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Number of players");

        scores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        player.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        player.setText("player:");

        points.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        points.setText("points:");

        missing.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        missing.setText("missing:");

        player_2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        player_2.setText("#");

        point_2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        point_2.setText("#");

        missing_2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        missing_2.setText("#");

        javax.swing.GroupLayout scoresLayout = new javax.swing.GroupLayout(scores);
        scores.setLayout(scoresLayout);
        scoresLayout.setHorizontalGroup(
            scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoresLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(player)
                        .addComponent(points))
                    .addComponent(missing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player_2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(point_2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missing_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        scoresLayout.setVerticalGroup(
            scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player)
                    .addComponent(player_2))
                .addGap(26, 26, 26)
                .addGroup(scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(points)
                    .addComponent(point_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(scoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missing)
                    .addComponent(missing_2))
                .addGap(21, 21, 21))
        );

        pairs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "pairs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout pairsLayout = new javax.swing.GroupLayout(pairs);
        pairs.setLayout(pairsLayout);
        pairsLayout.setHorizontalGroup(
            pairsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pairsLayout.setVerticalGroup(
            pairsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3" }));

        level.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        level.setText("level");

        about_of.setText("about of...");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tuerca.png"))); // NOI18N

        javax.swing.GroupLayout mesaLayout = new javax.swing.GroupLayout(mesa);
        mesa.setLayout(mesaLayout);
        mesaLayout.setHorizontalGroup(
            mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mesaLayout.createSequentialGroup()
                .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mesaLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mesaLayout.createSequentialGroup()
                        .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mesaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mesaLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mesaLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(mesaLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(play_2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mesaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(about_of)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(en)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(es)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mesaLayout.createSequentialGroup()
                        .addComponent(scores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mesaLayout.createSequentialGroup()
                        .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mesaLayout.createSequentialGroup()
                                .addComponent(dices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(mesaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(try_again)
                                .addGap(20, 20, 20)))
                        .addComponent(pairs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        mesaLayout.setVerticalGroup(
            mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mesaLayout.createSequentialGroup()
                .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mesaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(about_of)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(en)
                                .addComponent(es)))))
                .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mesaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(level)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(play_2))
                    .addGroup(mesaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mesaLayout.createSequentialGroup()
                                .addComponent(dices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(play)
                                    .addComponent(try_again)))
                            .addComponent(pairs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public Image getIconImage() {
   Image retValue = Toolkit.getDefaultToolkit().
         getImage(ClassLoader.getSystemResource("icons/car.png"));


   return retValue;
}
    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
       
        Random D = new Random();
//        int x = box.getSelectedIndex();
        int d1 = 0, d2 = 0;
        d1 = (int)(D.nextDouble()* 6 + 1);
        d2 = (int)(D.nextDouble()* 6 + 1);
        int sum = d1 + d2;
        String c = Integer.toString(sum);
        suma.setText(c);
        
    switch(d1){
            case 1:
            dice_1.setIcon(new ImageIcon(getClass().getResource("images/1.png")));
                break;
            case 2:
                dice_1.setIcon(new ImageIcon(getClass().getResource("images/2.png")));
                break;
            case 3:
                dice_1.setIcon(new ImageIcon(getClass().getResource("images/3.png")));               
                break;
            case 4:
                dice_1.setIcon(new ImageIcon(getClass().getResource("images/4.png")));            
                break;
            case 5:
                dice_1.setIcon(new ImageIcon(getClass().getResource("images/5.png")));       
                break;
            case 6:
                dice_1.setIcon(new ImageIcon(getClass().getResource("images/6.png")));           
                break;
            default:
                break;
        }
 switch(d2){
            case 1:
                dice_2.setIcon(new ImageIcon(getClass().getResource("images/1.png")));
                break;
            case 2:
                dice_2.setIcon(new ImageIcon(getClass().getResource("images/2.png")));
                break;
            case 3:
                dice_2.setIcon(new ImageIcon(getClass().getResource("images/3.png")));
                break;
            case 4:
                dice_2.setIcon(new ImageIcon(getClass().getResource("images/4.png")));
                break;
            case 5:
                dice_2.setIcon(new ImageIcon(getClass().getResource("images/5.png")));
                break;
            case 6:
                dice_2.setIcon(new ImageIcon(getClass().getResource("images/6.png")));
                break;
            default:
                break;
    }
    }//GEN-LAST:event_playActionPerformed

    private void try_againActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_try_againActionPerformed
        dice_1.setIcon(new ImageIcon(getClass().getResource("images/question.png")));
        dice_2.setIcon(new ImageIcon(getClass().getResource("images/question.png")));
        suma.setText("#");
    }//GEN-LAST:event_try_againActionPerformed

    private void esActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esActionPerformed
        en.setEnabled(true);
        es.setEnabled(false);
        title.setText("carrera numerica");
        play.setText("jugar");
        jLabel3.setText("cantidad de jugadores");
        play_2.setText("empezar juego");
        try_again.setText("Inténtalo de nuevo");
        dices.setBorder(javax.swing.BorderFactory.createTitledBorder("DADOS"));
        player.setText("jugador:");
        missing.setText("desaparecido:");
        points.setText("puntos:");
        level.setText("nivel");
        about_of.setText("acerca de...");
        pairs.setBorder(javax.swing.BorderFactory.createTitledBorder("pares"));
        scores.setBorder(javax.swing.BorderFactory.createTitledBorder("Puntuaciones"));
        this.setTitle("carrera numerica");
    }//GEN-LAST:event_esActionPerformed

    private void enActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enActionPerformed
        es.setEnabled(true);
        en.setEnabled(false);
        title.setText("number race");
        about_of.setText("about of...");
        level.setText("level");
        jLabel3.setText("Number of players");
        play.setText("play");
        play_2.setText("start game");
        try_again.setText("try again");
        dices.setBorder(javax.swing.BorderFactory.createTitledBorder("DICES"));
        player.setText("player:");
        missing.setText("missing:");
        points.setText("points:");
        pairs.setBorder(javax.swing.BorderFactory.createTitledBorder("pairs"));
        scores.setBorder(javax.swing.BorderFactory.createTitledBorder("Scores"));
        this.setTitle("number race");
    }//GEN-LAST:event_enActionPerformed
   
    private void play_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_2ActionPerformed

        play.setEnabled(true);
        try_again.setEnabled(true);
        play_2.setEnabled(false);
        
    }//GEN-LAST:event_play_2ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberRace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about_of;
    private javax.swing.JComboBox<String> box;
    private javax.swing.JLabel dice_1;
    private javax.swing.JLabel dice_2;
    private javax.swing.JPanel dices;
    private javax.swing.JButton en;
    private javax.swing.JButton es;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jugadores;
    private javax.swing.JLabel level;
    private javax.swing.JPanel mesa;
    private javax.swing.JLabel missing;
    private javax.swing.JLabel missing_2;
    private javax.swing.JPanel pairs;
    private javax.swing.JButton play;
    private javax.swing.JButton play_2;
    private javax.swing.JLabel player;
    private javax.swing.JLabel player_2;
    private javax.swing.JLabel point_2;
    private javax.swing.JLabel points;
    private javax.swing.JPanel scores;
    private javax.swing.JLabel suma;
    private javax.swing.JLabel title;
    private javax.swing.JButton try_again;
    // End of variables declaration//GEN-END:variables
}
