
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jhonatan
 */
public class NewJFrame extends javax.swing.JFrame {
     ArrayList<Integer> lista = new ArrayList<Integer>();
     int y2=4;
     private int counter[]=new int [5];
     private int counter2[]=new int [5];
         int i=1;
    int i2=4;
    int f=0;
    int c=0;
    private int counter[]=new int[10];
    private int counter1[]=new int[5];
    
    private int counter2[]=new int[5];
    private int counter3[]=new int[5];
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        borrar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton1)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

    String pi = borrar.getText();
    int c = Integer.parseInt(pi);    
    for (int i=1;i<=4;i++) {
        lista.add(i);
    }
    if (c<=4 && c>=1){
        lista.remove (c-1);
        y2--;
    }    
    for (int i=0;i<=y2-1;i++) {     
        System.out.println(lista.get(i));
    }
    System.out.println("---------------------------");
    
    
    int pi = 0;
    String cains2 = coins.getSelectedItem().toString();
    int cains = Integer.parseInt(cains2);

    Random D = new Random();
    pi = (int)(D.nextDouble()* 6 + 1);
    if(f==0){
    for (int y=0;y<=3;y++){
        counter[y]= cains;
    }
//    }
//    if (i==0){
//    if (counter[3] == 0){
//        counter[3]=0;
//
//    
//    }        
//    }else if (counter[i-1] == 0){
//        counter[i-1]=counter[i+1];
//        i--;
//    }else if (counter[i-1] >= 1){
    switch (i+1){
       
        case 0:
           play.setText("Spin around -> player 1");  
        break;
        case 1:
           play.setText("Spin around -> player 2");  
        break;
        case 2:
           play.setText("Spin around -> player 3");  
        break;
        case 3:
           play.setText("Spin around -> player 4");  
        break;
    
    }
    switch (pi){
        case 0:
           pirinola.setText("?");  
        break;
        case 1:
            pirinola.setText("Pon 1");
            System.out.println("pon 1");
            counter1[0]++;
            if (i==0){

               if(counter[3]>0){
                   counter[3]--;
               }else if(counter[3]==0){
                   counter[i-1]=0;
               }
            }else if(i>=1){
            counter[i-1]--;

            }else if(counter[i-1]==0){
                   counter[i-1]=0;
               }
            
            f=1;
 
        break;
        case 2:
           pirinola.setText("Pon 2");
           System.out.println("pon 2");
           if(counter[i]>1){
            counter1[0]=counter1[0]+2;
            if (i==0){
               if(counter[3]>=2){
                    counter[3]=counter[3]-2;                   
               }
            }else if(counter[i-1]>=2){
                counter[i-1]=counter[i-1]-2;
                if (counter[i-1]==1){
                    counter[i-1]=counter[i-1];
                }
            }
           }
            f=1;

        break;
        case 3:
           pirinola.setText("Toma 1");
           System.out.println("Toma 1");
           if (counter1[0]>0){
                counter1[0]--;
                if (i==0){
                   counter[3]++; 
                   if(counter[3]==0){
                       System.out.println("eliminado jugador: "+counter[3]);
                   }
                }else{
                counter[i-1]++;
                System.out.println("eliminado jugador: "+counter[i-1]);
                }
           }
            f=1;

        break;
        case 4:
           pirinola.setText("Toma 2");
           System.out.println("Toma 2");
           if (counter1[0]>=2){
                counter1[0]=counter1[0]-2;
                if (i==0){
                   counter[3]=counter[3]+2;                                   
                }else if(i>=1){
                    counter[i-1]=counter[i-1]+2;
                }
           }else if (counter[0]<2){
               pi = (int)(D.nextDouble()* 6 + 1);
           }
            f=1;           

        break;
        case 5:
           pirinola.setText("Toma todo");
           System.out.println("Toma todo");
            if (i==0){
               counter[3]=counter[3]+counter1[0]; 
                   counter1[0]=0;
            }else if (i>=1){
            counter[i-1]=counter[i-1]+counter1[0];
            counter1[0]=0;
            }
            counter1[0]=0;
            f=1;

        break;
        case 6:
          
           pirinola.setText("Todos ponen");
           System.out.println("Todos ponen");
           counter1[0]=counter1[0]+i2;
           for (int y=0;y<=3;y++){
               if (counter[y]>0){
                    counter[y]--;
               }else if (counter[y]==0){
                   counter1[0]--;
                   
               }
           }
           f=1;

        break;
    }

    for (int y=1;y<=4;y++){
        System.out.println("jugador "+y+" : "+counter[y-1]);
        
    }
    String acc2 = Integer.toString(counter1[0]);
    String co1 = Integer.toString(counter[0]);
    String co2 = Integer.toString(counter[1]);
    String co3 = Integer.toString(counter[2]);
    String co4 = Integer.toString(counter[3]);
    acc.setText(acc2);
    coins1.setText(co1);
    coins2.setText(co2);
    coins3.setText(co3);
    coins4.setText(co4);
    System.out.println("---------------------------------");
    i++;
    if (i==4){
        i=0;
    }
   switch (pi){
        case 1:
            pirinola.setText("Pon 1");
            System.out.println("pon 1");
            if (counter[i] == 0){
                counter1 = counter1;
            }else{
                counter[i]--;
                counter1++;
            }
            f=1;
            
        break;
        case 2:
            pirinola.setText("Pon 2");
            System.out.println("pon 2");
            if (counter[i] == 0){
                counter1 = counter1;
            }else if (counter[i] >= 2 ){
                counter[i] =counter[i] - 2;
                counter1 =counter1 + 2;
            }else{
                counter1 = counter1;
                counter[i] = counter[i];
            }
            f=1;
            
        break;
        case 3:
            pirinola.setText("toma 1");
            System.out.println("toma 1"); 
            if (counter[i] == 0){
                counter1 = counter1;
            }else if (counter1 >= 1) {
                counter1--;
                counter[i]++;
            }else{
                counter1 = counter1;
                counter[i] = counter[i];                        
            }
            f=1;
            
        break;
        case 4:
            pirinola.setText("toma 2");
            System.out.println("toma 2");
            if (counter1 == 0){
                counter[i] = counter[i];
            }else if (counter1 >= 2 ){
                counter1 =counter1 - 2;
                counter[i] =counter[i] + 2;
            }else{
                counter1 = counter1;
                counter[i] = counter[i];
            }
            f=1;       
        break;
        case 5:
            pirinola.setText("todos ponen");
            System.out.println("todos ponen");
            for (int y=0;y<=3;y++){
                if (counter[y] >= 1){
                    counter[y]--;
                }else{
                    counter[y] = counter[y];
                    counter1--;
                }
            }
            counter1 =counter1 + 4;
            f=1;
            
        break;
        case 6:
            pirinola.setText("toma todo");
            System.out.println("toma todo");
            counter1 = 0;
            counter[i] = counter[i] + counter1;
            f=1;        
        break;
    }
//    }else if (counter[i]==0){
//        counter[i]=counter[i+1];
//        i++;
//        if (i==3){
//        counter[3]=counter[0];
//        i=0;
//    }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField borrar;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
        case 1:
            System.out.println("pon 1");
            pirinola.setText("pon 1");
            if (i == 0){
                if (counter[i] == 0){
                    counter[i]=counter[i];
                }else if (counter[3] >= 1){
                    counter[3]--;
                    counter1++;
                }
            }else if (i > 0){
                if (counter[2] >= 1 && i == 3){
                    counter[2]--;
                    counter1++;
                }
                if (counter[1] >= 1 && i == 2){
                    counter[1]--;
                    counter1++;
                }
                if (counter[0] >= 1 && i == 1){
                    counter[0]--;
                    counter1++;
                }
                if (counter[3] >= 1 && i == 0){
                    counter[3]--;
                    counter1++;
                }                
            }
            f=1;
            break;
        case 2:
            System.out.println("pon 2");
            pirinola.setText("pon 2");
            if (counter[i]!=0){
                if (counter[i]>=2){
                    if (i == 0){
                        if (counter[i] == 0){
                            counter[i]=counter[i];
                        }else if (counter[3] >= 2){
                            counter[3]=counter[3]-2;
                            counter1 = counter1+2;
                        }
                    }else if (i > 0){
                        if (counter[2] >= 2 && i == 3){
                            counter[2]=counter[2]-2;
                            counter1= counter1+2;
                        }
                        if (counter[1] >= 2 && i == 2){
                            counter[1]=counter[1]-2;
                            counter1 = counter1+2;
                        }
                        if (counter[0] >= 2 && i == 1){
                            counter[0]=counter[1]-2;
                            counter1 = counter1+2;
                        }
                        if (counter[3] >= 2 && i == 0){
                            counter[3]=counter[1]-2;
                            counter1 = counter1+2;
                        }                
                    }
                }
            }else if (counter[i]==0){
                counter[i]=counter[i];
                counter1=counter1;
            }
                f=1;
                break;  
        case 3:
            System.out.println("toma 1");
            pirinola.setText("toma 1");
            if (counter[i]!=0){
                if (counter1>=1){
                    if (i == 0){
                        if (counter[i] == 0){
                            counter[i]=counter[i];
                        }else if (counter1 >= 1){
                            counter[3]++;
                            counter1--;
                        }
                    }else if (i > 0){
                        if (counter[2] >= 2 && i == 3){
                            counter[2]++;
                            counter1--;
                        }
                        if (counter[1] >= 2 && i == 2){
                            counter[1]++;
                            counter1--;
                        }
                        if (counter[0] >= 2 && i == 1){
                            counter[0]++;
                            counter1--;
                        }
                        if (counter[3] >= 2 && i == 0){
                            counter[3]++;
                            counter1--;
                        }                
                    }
                }
            }else if (counter[i]==0){
                counter[i]=counter[i];
                counter1=counter1;
            }
                f=1;
                break;
        case 4:
            System.out.println("toma 2");
            pirinola.setText("toma 2");
            if (counter[i]!=0){
                if (counter1>=2){
                    if (i == 0){
                        if (counter[i] == 0){
                            counter[i]=counter[i];
                        }else if (counter1 >= 1){
                            counter[3]=counter[3]+2;
                            counter1=counter1-2;
                        }
                    }else if (i > 0){
                        if (counter[2] >= 2 && i == 3){
                            counter[2]=counter[3]+2;
                            counter1=counter1-2;
                        }
                        if (counter[1] >= 2 && i == 2){
                            counter[1]=counter[3]+2;
                            counter1=counter1-2;
                        }
                        if (counter[0] >= 2 && i == 1){
                            counter[0]=counter[3]+2;
                            counter1=counter1-2;
                        }
                        if (counter[3] >= 2 && i == 0){
                            counter[3]=counter[3]+2;
                            counter1=counter1-2;
                        }                
                    }
                }
            }else if (counter[i]==0){
                counter[i]=counter[i];
                counter1=counter1;
            }
                f=1;
                break; 
        case 5:
            System.out.println("toma todo");
            pirinola.setText("toma todo");
            if (counter[i]!=0){
                if (counter1>=1){
                    if (i == 0){
                        if (counter[i] == 0){
                            counter[i]=counter[i];
                        }else if (counter1 >= 1){
                            counter[3]=counter[3]+counter1;
                            counter1=0;
                        }
                    }else if (i > 0){
                        if (counter[2] >= 2 && i == 3){
                            counter[2]=counter[3]+counter1;
                            counter1=0;
                        }
                        if (counter[1] >= 2 && i == 2){
                            counter[1]=counter[3]+counter1;
                            counter1=0;
                        }
                        if (counter[0] >= 2 && i == 1){
                            counter[0]=counter[3]+counter1;
                            counter1=0;
                        }
                        if (counter[3] >= 2 && i == 0){
                            counter[3]=counter[3]+counter1;
                            counter1=0;
                        }                
                    }
                }
            }else if (counter[i]==0){
                counter[i]=counter[i];
                counter1=counter1;
            }
                f=1;
                break;
        case 6:
            System.out.println("todo ponen");
            pirinola.setText("todo ponen");
            if (counter[i]!=0){
                if (counter1>=1){
                    if (i == 0){
                        if (counter[i] == 0){
                            counter[i]=counter[i];
                        }else if (counter1 >= 1){
                            counter[3]--;
                            counter1=counter1+y2;
                        }
                    }else if (i > 0){
                        if (counter[2] >= 2 && i == 3){
                            counter[3]--;
                            counter1=counter1+y2;
                        }
                        if (counter[1] >= 2 && i == 2){
                            counter[3]--;
                            counter1=counter1+y2;
                        }
                        if (counter[0] >= 2 && i == 1){
                            counter[3]--;
                            counter1=counter1+y2;
                        }
                        if (counter[3] >= 2 && i == 0){
                            counter[3]--;
                            counter1=counter1+y2;
                        }                
                    }
                }
            }else if (counter[i]==0){
                counter[i]=counter[i];
                counter1=counter1;
            }
                f=1;
                break;